name: Frontend Docker

on:
  push:
  pull_request:

jobs:
  build:
    name: Build Docker Container
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Make Application in Docker
      run: make app