name: Frontend Lint

on:
  push:
  pull_request:

jobs:
  build:
    name: Check Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: npm i

    - name: Install CI checks
      run: npm ci

    - name: Check types
      run: npm run typecheck

    - name: Lint with Biome
      run: npm run check:code

    - name: Lint styles
      run: npm run lint:styles

    - name: Test Production Build
      run: npm run build

